package com.hehanpeng.ssm.module.goods.pojo;

import java.math.BigDecimal;

public class Goods {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.goods_id
     *
     * @mbggenerated
     */
    private String goodsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.goods_name
     *
     * @mbggenerated
     */
    private String goodsName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.goods_unit
     *
     * @mbggenerated
     */
    private String goodsUnit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.goods_type
     *
     * @mbggenerated
     */
    private String goodsType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.goods_color
     *
     * @mbggenerated
     */
    private String goodsColor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.goods_store
     *
     * @mbggenerated
     */
    private Integer goodsStore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.goods_limit
     *
     * @mbggenerated
     */
    private Integer goodsLimit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.goods_commission
     *
     * @mbggenerated
     */
    private BigDecimal goodsCommission;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.goods_producer
     *
     * @mbggenerated
     */
    private String goodsProducer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.goods_remark
     *
     * @mbggenerated
     */
    private String goodsRemark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.goods_sel_price
     *
     * @mbggenerated
     */
    private BigDecimal goodsSelPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.goods_buy_price
     *
     * @mbggenerated
     */
    private BigDecimal goodsBuyPrice;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.goods_id
     *
     * @return the value of goods.goods_id
     *
     * @mbggenerated
     */
    public String getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.goods_id
     *
     * @param goodsId the value for goods.goods_id
     *
     * @mbggenerated
     */
    public void setGoodsId(String goodsId) {
        this.goodsId = goodsId == null ? null : goodsId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.goods_name
     *
     * @return the value of goods.goods_name
     *
     * @mbggenerated
     */
    public String getGoodsName() {
        return goodsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.goods_name
     *
     * @param goodsName the value for goods.goods_name
     *
     * @mbggenerated
     */
    public void setGoodsName(String goodsName) {
        this.goodsName = goodsName == null ? null : goodsName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.goods_unit
     *
     * @return the value of goods.goods_unit
     *
     * @mbggenerated
     */
    public String getGoodsUnit() {
        return goodsUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.goods_unit
     *
     * @param goodsUnit the value for goods.goods_unit
     *
     * @mbggenerated
     */
    public void setGoodsUnit(String goodsUnit) {
        this.goodsUnit = goodsUnit == null ? null : goodsUnit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.goods_type
     *
     * @return the value of goods.goods_type
     *
     * @mbggenerated
     */
    public String getGoodsType() {
        return goodsType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.goods_type
     *
     * @param goodsType the value for goods.goods_type
     *
     * @mbggenerated
     */
    public void setGoodsType(String goodsType) {
        this.goodsType = goodsType == null ? null : goodsType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.goods_color
     *
     * @return the value of goods.goods_color
     *
     * @mbggenerated
     */
    public String getGoodsColor() {
        return goodsColor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.goods_color
     *
     * @param goodsColor the value for goods.goods_color
     *
     * @mbggenerated
     */
    public void setGoodsColor(String goodsColor) {
        this.goodsColor = goodsColor == null ? null : goodsColor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.goods_store
     *
     * @return the value of goods.goods_store
     *
     * @mbggenerated
     */
    public Integer getGoodsStore() {
        return goodsStore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.goods_store
     *
     * @param goodsStore the value for goods.goods_store
     *
     * @mbggenerated
     */
    public void setGoodsStore(Integer goodsStore) {
        this.goodsStore = goodsStore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.goods_limit
     *
     * @return the value of goods.goods_limit
     *
     * @mbggenerated
     */
    public Integer getGoodsLimit() {
        return goodsLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.goods_limit
     *
     * @param goodsLimit the value for goods.goods_limit
     *
     * @mbggenerated
     */
    public void setGoodsLimit(Integer goodsLimit) {
        this.goodsLimit = goodsLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.goods_commission
     *
     * @return the value of goods.goods_commission
     *
     * @mbggenerated
     */
    public BigDecimal getGoodsCommission() {
        return goodsCommission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.goods_commission
     *
     * @param goodsCommission the value for goods.goods_commission
     *
     * @mbggenerated
     */
    public void setGoodsCommission(BigDecimal goodsCommission) {
        this.goodsCommission = goodsCommission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.goods_producer
     *
     * @return the value of goods.goods_producer
     *
     * @mbggenerated
     */
    public String getGoodsProducer() {
        return goodsProducer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.goods_producer
     *
     * @param goodsProducer the value for goods.goods_producer
     *
     * @mbggenerated
     */
    public void setGoodsProducer(String goodsProducer) {
        this.goodsProducer = goodsProducer == null ? null : goodsProducer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.goods_remark
     *
     * @return the value of goods.goods_remark
     *
     * @mbggenerated
     */
    public String getGoodsRemark() {
        return goodsRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.goods_remark
     *
     * @param goodsRemark the value for goods.goods_remark
     *
     * @mbggenerated
     */
    public void setGoodsRemark(String goodsRemark) {
        this.goodsRemark = goodsRemark == null ? null : goodsRemark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.goods_sel_price
     *
     * @return the value of goods.goods_sel_price
     *
     * @mbggenerated
     */
    public BigDecimal getGoodsSelPrice() {
        return goodsSelPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.goods_sel_price
     *
     * @param goodsSelPrice the value for goods.goods_sel_price
     *
     * @mbggenerated
     */
    public void setGoodsSelPrice(BigDecimal goodsSelPrice) {
        this.goodsSelPrice = goodsSelPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.goods_buy_price
     *
     * @return the value of goods.goods_buy_price
     *
     * @mbggenerated
     */
    public BigDecimal getGoodsBuyPrice() {
        return goodsBuyPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.goods_buy_price
     *
     * @param goodsBuyPrice the value for goods.goods_buy_price
     *
     * @mbggenerated
     */
    public void setGoodsBuyPrice(BigDecimal goodsBuyPrice) {
        this.goodsBuyPrice = goodsBuyPrice;
    }
}