package com.hehanpeng.ssm.module.accountRecods.mapper;

import com.hehanpeng.ssm.module.accountRecods.pojo.AccountRecords;
import com.hehanpeng.ssm.module.common.mapper.BaseMapper;

import java.util.List;
import java.util.Map;

public interface AccountRecordsMapper extends BaseMapper<AccountRecordsMapper> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_records
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String arId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_records
     *
     * @mbggenerated
     */
    int insert(AccountRecords record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_records
     *
     * @mbggenerated
     */
    int insertSelective(AccountRecords record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_records
     *
     * @mbggenerated
     */
    AccountRecords selectByPrimaryKey(String arId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_records
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AccountRecords record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_records
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AccountRecords record);

    public List<Map<String, Object>> selectSupplierPayable(Map<String, String> paramMap);
}