package com.generator.mapper;

import com.generator.pojo.BuyOrder;

public interface BuyOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buy_order
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String boId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buy_order
     *
     * @mbggenerated
     */
    int insert(BuyOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buy_order
     *
     * @mbggenerated
     */
    int insertSelective(BuyOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buy_order
     *
     * @mbggenerated
     */
    BuyOrder selectByPrimaryKey(String boId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buy_order
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(BuyOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buy_order
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(BuyOrder record);
}