package com.generator.mapper;

import com.generator.pojo.ReturnOrderDetail;

public interface ReturnOrderDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table return_order_detail
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String rodId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table return_order_detail
     *
     * @mbggenerated
     */
    int insert(ReturnOrderDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table return_order_detail
     *
     * @mbggenerated
     */
    int insertSelective(ReturnOrderDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table return_order_detail
     *
     * @mbggenerated
     */
    ReturnOrderDetail selectByPrimaryKey(String rodId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table return_order_detail
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ReturnOrderDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table return_order_detail
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(ReturnOrderDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table return_order_detail
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ReturnOrderDetail record);
}