package com.generator.mapper;

import com.generator.pojo.ReturnOrder;

public interface ReturnOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table return_order
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String roId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table return_order
     *
     * @mbggenerated
     */
    int insert(ReturnOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table return_order
     *
     * @mbggenerated
     */
    int insertSelective(ReturnOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table return_order
     *
     * @mbggenerated
     */
    ReturnOrder selectByPrimaryKey(String roId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table return_order
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ReturnOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table return_order
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ReturnOrder record);
}