package com.generator.pojo;

import java.math.BigDecimal;
import java.util.Date;

public class BuyOrder {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buy_order.bo_id
     *
     * @mbggenerated
     */
    private String boId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buy_order.sup_id
     *
     * @mbggenerated
     */
    private Integer supId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buy_order.sh_id
     *
     * @mbggenerated
     */
    private String shId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buy_order.bo_date
     *
     * @mbggenerated
     */
    private Date boDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buy_order.bo_payable
     *
     * @mbggenerated
     */
    private BigDecimal boPayable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buy_order.bo_paid
     *
     * @mbggenerated
     */
    private BigDecimal boPaid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buy_order.bo_arrears
     *
     * @mbggenerated
     */
    private BigDecimal boArrears;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buy_order.bo_original
     *
     * @mbggenerated
     */
    private String boOriginal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buy_order.bo_remark
     *
     * @mbggenerated
     */
    private String boRemark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buy_order.bo_attn
     *
     * @mbggenerated
     */
    private String boAttn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buy_order.bo_operator
     *
     * @mbggenerated
     */
    private Integer boOperator;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buy_order.bo_id
     *
     * @return the value of buy_order.bo_id
     *
     * @mbggenerated
     */
    public String getBoId() {
        return boId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buy_order.bo_id
     *
     * @param boId the value for buy_order.bo_id
     *
     * @mbggenerated
     */
    public void setBoId(String boId) {
        this.boId = boId == null ? null : boId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buy_order.sup_id
     *
     * @return the value of buy_order.sup_id
     *
     * @mbggenerated
     */
    public Integer getSupId() {
        return supId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buy_order.sup_id
     *
     * @param supId the value for buy_order.sup_id
     *
     * @mbggenerated
     */
    public void setSupId(Integer supId) {
        this.supId = supId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buy_order.sh_id
     *
     * @return the value of buy_order.sh_id
     *
     * @mbggenerated
     */
    public String getShId() {
        return shId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buy_order.sh_id
     *
     * @param shId the value for buy_order.sh_id
     *
     * @mbggenerated
     */
    public void setShId(String shId) {
        this.shId = shId == null ? null : shId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buy_order.bo_date
     *
     * @return the value of buy_order.bo_date
     *
     * @mbggenerated
     */
    public Date getBoDate() {
        return boDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buy_order.bo_date
     *
     * @param boDate the value for buy_order.bo_date
     *
     * @mbggenerated
     */
    public void setBoDate(Date boDate) {
        this.boDate = boDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buy_order.bo_payable
     *
     * @return the value of buy_order.bo_payable
     *
     * @mbggenerated
     */
    public BigDecimal getBoPayable() {
        return boPayable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buy_order.bo_payable
     *
     * @param boPayable the value for buy_order.bo_payable
     *
     * @mbggenerated
     */
    public void setBoPayable(BigDecimal boPayable) {
        this.boPayable = boPayable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buy_order.bo_paid
     *
     * @return the value of buy_order.bo_paid
     *
     * @mbggenerated
     */
    public BigDecimal getBoPaid() {
        return boPaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buy_order.bo_paid
     *
     * @param boPaid the value for buy_order.bo_paid
     *
     * @mbggenerated
     */
    public void setBoPaid(BigDecimal boPaid) {
        this.boPaid = boPaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buy_order.bo_arrears
     *
     * @return the value of buy_order.bo_arrears
     *
     * @mbggenerated
     */
    public BigDecimal getBoArrears() {
        return boArrears;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buy_order.bo_arrears
     *
     * @param boArrears the value for buy_order.bo_arrears
     *
     * @mbggenerated
     */
    public void setBoArrears(BigDecimal boArrears) {
        this.boArrears = boArrears;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buy_order.bo_original
     *
     * @return the value of buy_order.bo_original
     *
     * @mbggenerated
     */
    public String getBoOriginal() {
        return boOriginal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buy_order.bo_original
     *
     * @param boOriginal the value for buy_order.bo_original
     *
     * @mbggenerated
     */
    public void setBoOriginal(String boOriginal) {
        this.boOriginal = boOriginal == null ? null : boOriginal.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buy_order.bo_remark
     *
     * @return the value of buy_order.bo_remark
     *
     * @mbggenerated
     */
    public String getBoRemark() {
        return boRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buy_order.bo_remark
     *
     * @param boRemark the value for buy_order.bo_remark
     *
     * @mbggenerated
     */
    public void setBoRemark(String boRemark) {
        this.boRemark = boRemark == null ? null : boRemark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buy_order.bo_attn
     *
     * @return the value of buy_order.bo_attn
     *
     * @mbggenerated
     */
    public String getBoAttn() {
        return boAttn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buy_order.bo_attn
     *
     * @param boAttn the value for buy_order.bo_attn
     *
     * @mbggenerated
     */
    public void setBoAttn(String boAttn) {
        this.boAttn = boAttn == null ? null : boAttn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buy_order.bo_operator
     *
     * @return the value of buy_order.bo_operator
     *
     * @mbggenerated
     */
    public Integer getBoOperator() {
        return boOperator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buy_order.bo_operator
     *
     * @param boOperator the value for buy_order.bo_operator
     *
     * @mbggenerated
     */
    public void setBoOperator(Integer boOperator) {
        this.boOperator = boOperator;
    }
}