package com.generator.pojo;

import java.math.BigDecimal;

public class BuyOrderDetail {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buy_order_detail.bod_id
     *
     * @mbggenerated
     */
    private String bodId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buy_order_detail.goods_id
     *
     * @mbggenerated
     */
    private String goodsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buy_order_detail.goods_name
     *
     * @mbggenerated
     */
    private String goodsName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buy_order_detail.goods_unit
     *
     * @mbggenerated
     */
    private String goodsUnit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buy_order_detail.goods_type
     *
     * @mbggenerated
     */
    private String goodsType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buy_order_detail.goods_color
     *
     * @mbggenerated
     */
    private String goodsColor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buy_order_detail.bod_amount
     *
     * @mbggenerated
     */
    private Integer bodAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buy_order_detail.bod_buy_price
     *
     * @mbggenerated
     */
    private BigDecimal bodBuyPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buy_order_detail.bod_total_price
     *
     * @mbggenerated
     */
    private BigDecimal bodTotalPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buy_order_detail.bo_id
     *
     * @mbggenerated
     */
    private String boId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buy_order_detail.bod_imei_list
     *
     * @mbggenerated
     */
    private String bodImeiList;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buy_order_detail.bod_id
     *
     * @return the value of buy_order_detail.bod_id
     *
     * @mbggenerated
     */
    public String getBodId() {
        return bodId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buy_order_detail.bod_id
     *
     * @param bodId the value for buy_order_detail.bod_id
     *
     * @mbggenerated
     */
    public void setBodId(String bodId) {
        this.bodId = bodId == null ? null : bodId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buy_order_detail.goods_id
     *
     * @return the value of buy_order_detail.goods_id
     *
     * @mbggenerated
     */
    public String getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buy_order_detail.goods_id
     *
     * @param goodsId the value for buy_order_detail.goods_id
     *
     * @mbggenerated
     */
    public void setGoodsId(String goodsId) {
        this.goodsId = goodsId == null ? null : goodsId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buy_order_detail.goods_name
     *
     * @return the value of buy_order_detail.goods_name
     *
     * @mbggenerated
     */
    public String getGoodsName() {
        return goodsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buy_order_detail.goods_name
     *
     * @param goodsName the value for buy_order_detail.goods_name
     *
     * @mbggenerated
     */
    public void setGoodsName(String goodsName) {
        this.goodsName = goodsName == null ? null : goodsName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buy_order_detail.goods_unit
     *
     * @return the value of buy_order_detail.goods_unit
     *
     * @mbggenerated
     */
    public String getGoodsUnit() {
        return goodsUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buy_order_detail.goods_unit
     *
     * @param goodsUnit the value for buy_order_detail.goods_unit
     *
     * @mbggenerated
     */
    public void setGoodsUnit(String goodsUnit) {
        this.goodsUnit = goodsUnit == null ? null : goodsUnit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buy_order_detail.goods_type
     *
     * @return the value of buy_order_detail.goods_type
     *
     * @mbggenerated
     */
    public String getGoodsType() {
        return goodsType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buy_order_detail.goods_type
     *
     * @param goodsType the value for buy_order_detail.goods_type
     *
     * @mbggenerated
     */
    public void setGoodsType(String goodsType) {
        this.goodsType = goodsType == null ? null : goodsType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buy_order_detail.goods_color
     *
     * @return the value of buy_order_detail.goods_color
     *
     * @mbggenerated
     */
    public String getGoodsColor() {
        return goodsColor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buy_order_detail.goods_color
     *
     * @param goodsColor the value for buy_order_detail.goods_color
     *
     * @mbggenerated
     */
    public void setGoodsColor(String goodsColor) {
        this.goodsColor = goodsColor == null ? null : goodsColor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buy_order_detail.bod_amount
     *
     * @return the value of buy_order_detail.bod_amount
     *
     * @mbggenerated
     */
    public Integer getBodAmount() {
        return bodAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buy_order_detail.bod_amount
     *
     * @param bodAmount the value for buy_order_detail.bod_amount
     *
     * @mbggenerated
     */
    public void setBodAmount(Integer bodAmount) {
        this.bodAmount = bodAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buy_order_detail.bod_buy_price
     *
     * @return the value of buy_order_detail.bod_buy_price
     *
     * @mbggenerated
     */
    public BigDecimal getBodBuyPrice() {
        return bodBuyPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buy_order_detail.bod_buy_price
     *
     * @param bodBuyPrice the value for buy_order_detail.bod_buy_price
     *
     * @mbggenerated
     */
    public void setBodBuyPrice(BigDecimal bodBuyPrice) {
        this.bodBuyPrice = bodBuyPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buy_order_detail.bod_total_price
     *
     * @return the value of buy_order_detail.bod_total_price
     *
     * @mbggenerated
     */
    public BigDecimal getBodTotalPrice() {
        return bodTotalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buy_order_detail.bod_total_price
     *
     * @param bodTotalPrice the value for buy_order_detail.bod_total_price
     *
     * @mbggenerated
     */
    public void setBodTotalPrice(BigDecimal bodTotalPrice) {
        this.bodTotalPrice = bodTotalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buy_order_detail.bo_id
     *
     * @return the value of buy_order_detail.bo_id
     *
     * @mbggenerated
     */
    public String getBoId() {
        return boId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buy_order_detail.bo_id
     *
     * @param boId the value for buy_order_detail.bo_id
     *
     * @mbggenerated
     */
    public void setBoId(String boId) {
        this.boId = boId == null ? null : boId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buy_order_detail.bod_imei_list
     *
     * @return the value of buy_order_detail.bod_imei_list
     *
     * @mbggenerated
     */
    public String getBodImeiList() {
        return bodImeiList;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buy_order_detail.bod_imei_list
     *
     * @param bodImeiList the value for buy_order_detail.bod_imei_list
     *
     * @mbggenerated
     */
    public void setBodImeiList(String bodImeiList) {
        this.bodImeiList = bodImeiList == null ? null : bodImeiList.trim();
    }
}