package com.generator.pojo;

import java.math.BigDecimal;

public class ReturnOrderDetail {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column return_order_detail.rod_id
     *
     * @mbggenerated
     */
    private String rodId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column return_order_detail.goods_id
     *
     * @mbggenerated
     */
    private String goodsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column return_order_detail.goods_unit
     *
     * @mbggenerated
     */
    private String goodsUnit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column return_order_detail.goods_name
     *
     * @mbggenerated
     */
    private String goodsName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column return_order_detail.goods_type
     *
     * @mbggenerated
     */
    private String goodsType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column return_order_detail.goods_color
     *
     * @mbggenerated
     */
    private String goodsColor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column return_order_detail.rod_amount
     *
     * @mbggenerated
     */
    private Integer rodAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column return_order_detail.rod_return_price
     *
     * @mbggenerated
     */
    private BigDecimal rodReturnPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column return_order_detail.rod_total_price
     *
     * @mbggenerated
     */
    private BigDecimal rodTotalPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column return_order_detail.ro_id
     *
     * @mbggenerated
     */
    private String roId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column return_order_detail.rod_imei_list
     *
     * @mbggenerated
     */
    private String rodImeiList;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column return_order_detail.rod_id
     *
     * @return the value of return_order_detail.rod_id
     *
     * @mbggenerated
     */
    public String getRodId() {
        return rodId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column return_order_detail.rod_id
     *
     * @param rodId the value for return_order_detail.rod_id
     *
     * @mbggenerated
     */
    public void setRodId(String rodId) {
        this.rodId = rodId == null ? null : rodId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column return_order_detail.goods_id
     *
     * @return the value of return_order_detail.goods_id
     *
     * @mbggenerated
     */
    public String getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column return_order_detail.goods_id
     *
     * @param goodsId the value for return_order_detail.goods_id
     *
     * @mbggenerated
     */
    public void setGoodsId(String goodsId) {
        this.goodsId = goodsId == null ? null : goodsId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column return_order_detail.goods_unit
     *
     * @return the value of return_order_detail.goods_unit
     *
     * @mbggenerated
     */
    public String getGoodsUnit() {
        return goodsUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column return_order_detail.goods_unit
     *
     * @param goodsUnit the value for return_order_detail.goods_unit
     *
     * @mbggenerated
     */
    public void setGoodsUnit(String goodsUnit) {
        this.goodsUnit = goodsUnit == null ? null : goodsUnit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column return_order_detail.goods_name
     *
     * @return the value of return_order_detail.goods_name
     *
     * @mbggenerated
     */
    public String getGoodsName() {
        return goodsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column return_order_detail.goods_name
     *
     * @param goodsName the value for return_order_detail.goods_name
     *
     * @mbggenerated
     */
    public void setGoodsName(String goodsName) {
        this.goodsName = goodsName == null ? null : goodsName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column return_order_detail.goods_type
     *
     * @return the value of return_order_detail.goods_type
     *
     * @mbggenerated
     */
    public String getGoodsType() {
        return goodsType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column return_order_detail.goods_type
     *
     * @param goodsType the value for return_order_detail.goods_type
     *
     * @mbggenerated
     */
    public void setGoodsType(String goodsType) {
        this.goodsType = goodsType == null ? null : goodsType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column return_order_detail.goods_color
     *
     * @return the value of return_order_detail.goods_color
     *
     * @mbggenerated
     */
    public String getGoodsColor() {
        return goodsColor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column return_order_detail.goods_color
     *
     * @param goodsColor the value for return_order_detail.goods_color
     *
     * @mbggenerated
     */
    public void setGoodsColor(String goodsColor) {
        this.goodsColor = goodsColor == null ? null : goodsColor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column return_order_detail.rod_amount
     *
     * @return the value of return_order_detail.rod_amount
     *
     * @mbggenerated
     */
    public Integer getRodAmount() {
        return rodAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column return_order_detail.rod_amount
     *
     * @param rodAmount the value for return_order_detail.rod_amount
     *
     * @mbggenerated
     */
    public void setRodAmount(Integer rodAmount) {
        this.rodAmount = rodAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column return_order_detail.rod_return_price
     *
     * @return the value of return_order_detail.rod_return_price
     *
     * @mbggenerated
     */
    public BigDecimal getRodReturnPrice() {
        return rodReturnPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column return_order_detail.rod_return_price
     *
     * @param rodReturnPrice the value for return_order_detail.rod_return_price
     *
     * @mbggenerated
     */
    public void setRodReturnPrice(BigDecimal rodReturnPrice) {
        this.rodReturnPrice = rodReturnPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column return_order_detail.rod_total_price
     *
     * @return the value of return_order_detail.rod_total_price
     *
     * @mbggenerated
     */
    public BigDecimal getRodTotalPrice() {
        return rodTotalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column return_order_detail.rod_total_price
     *
     * @param rodTotalPrice the value for return_order_detail.rod_total_price
     *
     * @mbggenerated
     */
    public void setRodTotalPrice(BigDecimal rodTotalPrice) {
        this.rodTotalPrice = rodTotalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column return_order_detail.ro_id
     *
     * @return the value of return_order_detail.ro_id
     *
     * @mbggenerated
     */
    public String getRoId() {
        return roId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column return_order_detail.ro_id
     *
     * @param roId the value for return_order_detail.ro_id
     *
     * @mbggenerated
     */
    public void setRoId(String roId) {
        this.roId = roId == null ? null : roId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column return_order_detail.rod_imei_list
     *
     * @return the value of return_order_detail.rod_imei_list
     *
     * @mbggenerated
     */
    public String getRodImeiList() {
        return rodImeiList;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column return_order_detail.rod_imei_list
     *
     * @param rodImeiList the value for return_order_detail.rod_imei_list
     *
     * @mbggenerated
     */
    public void setRodImeiList(String rodImeiList) {
        this.rodImeiList = rodImeiList == null ? null : rodImeiList.trim();
    }
}