package com.generator.pojo;

import java.math.BigDecimal;
import java.util.Date;

public class ReturnOrder {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column return_order.ro_id
     *
     * @mbggenerated
     */
    private String roId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column return_order.sup_id
     *
     * @mbggenerated
     */
    private Integer supId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column return_order.sh_id
     *
     * @mbggenerated
     */
    private String shId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column return_order.ro_date
     *
     * @mbggenerated
     */
    private Date roDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column return_order.ro_payable
     *
     * @mbggenerated
     */
    private BigDecimal roPayable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column return_order.ro_paid
     *
     * @mbggenerated
     */
    private BigDecimal roPaid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column return_order.ro_remark
     *
     * @mbggenerated
     */
    private String roRemark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column return_order.ro_attn
     *
     * @mbggenerated
     */
    private String roAttn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column return_order.ro_operator
     *
     * @mbggenerated
     */
    private Integer roOperator;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column return_order.ro_id
     *
     * @return the value of return_order.ro_id
     *
     * @mbggenerated
     */
    public String getRoId() {
        return roId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column return_order.ro_id
     *
     * @param roId the value for return_order.ro_id
     *
     * @mbggenerated
     */
    public void setRoId(String roId) {
        this.roId = roId == null ? null : roId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column return_order.sup_id
     *
     * @return the value of return_order.sup_id
     *
     * @mbggenerated
     */
    public Integer getSupId() {
        return supId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column return_order.sup_id
     *
     * @param supId the value for return_order.sup_id
     *
     * @mbggenerated
     */
    public void setSupId(Integer supId) {
        this.supId = supId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column return_order.sh_id
     *
     * @return the value of return_order.sh_id
     *
     * @mbggenerated
     */
    public String getShId() {
        return shId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column return_order.sh_id
     *
     * @param shId the value for return_order.sh_id
     *
     * @mbggenerated
     */
    public void setShId(String shId) {
        this.shId = shId == null ? null : shId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column return_order.ro_date
     *
     * @return the value of return_order.ro_date
     *
     * @mbggenerated
     */
    public Date getRoDate() {
        return roDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column return_order.ro_date
     *
     * @param roDate the value for return_order.ro_date
     *
     * @mbggenerated
     */
    public void setRoDate(Date roDate) {
        this.roDate = roDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column return_order.ro_payable
     *
     * @return the value of return_order.ro_payable
     *
     * @mbggenerated
     */
    public BigDecimal getRoPayable() {
        return roPayable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column return_order.ro_payable
     *
     * @param roPayable the value for return_order.ro_payable
     *
     * @mbggenerated
     */
    public void setRoPayable(BigDecimal roPayable) {
        this.roPayable = roPayable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column return_order.ro_paid
     *
     * @return the value of return_order.ro_paid
     *
     * @mbggenerated
     */
    public BigDecimal getRoPaid() {
        return roPaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column return_order.ro_paid
     *
     * @param roPaid the value for return_order.ro_paid
     *
     * @mbggenerated
     */
    public void setRoPaid(BigDecimal roPaid) {
        this.roPaid = roPaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column return_order.ro_remark
     *
     * @return the value of return_order.ro_remark
     *
     * @mbggenerated
     */
    public String getRoRemark() {
        return roRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column return_order.ro_remark
     *
     * @param roRemark the value for return_order.ro_remark
     *
     * @mbggenerated
     */
    public void setRoRemark(String roRemark) {
        this.roRemark = roRemark == null ? null : roRemark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column return_order.ro_attn
     *
     * @return the value of return_order.ro_attn
     *
     * @mbggenerated
     */
    public String getRoAttn() {
        return roAttn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column return_order.ro_attn
     *
     * @param roAttn the value for return_order.ro_attn
     *
     * @mbggenerated
     */
    public void setRoAttn(String roAttn) {
        this.roAttn = roAttn == null ? null : roAttn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column return_order.ro_operator
     *
     * @return the value of return_order.ro_operator
     *
     * @mbggenerated
     */
    public Integer getRoOperator() {
        return roOperator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column return_order.ro_operator
     *
     * @param roOperator the value for return_order.ro_operator
     *
     * @mbggenerated
     */
    public void setRoOperator(Integer roOperator) {
        this.roOperator = roOperator;
    }
}