package com.generator.pojo;

import java.math.BigDecimal;
import java.util.Date;

public class Stock {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock.stock_id
     *
     * @mbggenerated
     */
    private String stockId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock.sh_id
     *
     * @mbggenerated
     */
    private String shId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock.goods_id
     *
     * @mbggenerated
     */
    private String goodsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock.stock_firstdate
     *
     * @mbggenerated
     */
    private Date stockFirstdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock.stock_lastdate
     *
     * @mbggenerated
     */
    private Date stockLastdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock.stock_amount
     *
     * @mbggenerated
     */
    private Integer stockAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock.stock_price
     *
     * @mbggenerated
     */
    private BigDecimal stockPrice;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock.stock_id
     *
     * @return the value of stock.stock_id
     *
     * @mbggenerated
     */
    public String getStockId() {
        return stockId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock.stock_id
     *
     * @param stockId the value for stock.stock_id
     *
     * @mbggenerated
     */
    public void setStockId(String stockId) {
        this.stockId = stockId == null ? null : stockId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock.sh_id
     *
     * @return the value of stock.sh_id
     *
     * @mbggenerated
     */
    public String getShId() {
        return shId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock.sh_id
     *
     * @param shId the value for stock.sh_id
     *
     * @mbggenerated
     */
    public void setShId(String shId) {
        this.shId = shId == null ? null : shId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock.goods_id
     *
     * @return the value of stock.goods_id
     *
     * @mbggenerated
     */
    public String getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock.goods_id
     *
     * @param goodsId the value for stock.goods_id
     *
     * @mbggenerated
     */
    public void setGoodsId(String goodsId) {
        this.goodsId = goodsId == null ? null : goodsId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock.stock_firstdate
     *
     * @return the value of stock.stock_firstdate
     *
     * @mbggenerated
     */
    public Date getStockFirstdate() {
        return stockFirstdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock.stock_firstdate
     *
     * @param stockFirstdate the value for stock.stock_firstdate
     *
     * @mbggenerated
     */
    public void setStockFirstdate(Date stockFirstdate) {
        this.stockFirstdate = stockFirstdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock.stock_lastdate
     *
     * @return the value of stock.stock_lastdate
     *
     * @mbggenerated
     */
    public Date getStockLastdate() {
        return stockLastdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock.stock_lastdate
     *
     * @param stockLastdate the value for stock.stock_lastdate
     *
     * @mbggenerated
     */
    public void setStockLastdate(Date stockLastdate) {
        this.stockLastdate = stockLastdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock.stock_amount
     *
     * @return the value of stock.stock_amount
     *
     * @mbggenerated
     */
    public Integer getStockAmount() {
        return stockAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock.stock_amount
     *
     * @param stockAmount the value for stock.stock_amount
     *
     * @mbggenerated
     */
    public void setStockAmount(Integer stockAmount) {
        this.stockAmount = stockAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock.stock_price
     *
     * @return the value of stock.stock_price
     *
     * @mbggenerated
     */
    public BigDecimal getStockPrice() {
        return stockPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock.stock_price
     *
     * @param stockPrice the value for stock.stock_price
     *
     * @mbggenerated
     */
    public void setStockPrice(BigDecimal stockPrice) {
        this.stockPrice = stockPrice;
    }
}