package com.generator.pojo;

public class StoreHouse {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store_house.sh_id
     *
     * @mbggenerated
     */
    private String shId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store_house.sh_name
     *
     * @mbggenerated
     */
    private String shName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store_house.sh_responsible
     *
     * @mbggenerated
     */
    private String shResponsible;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store_house.sh_phone
     *
     * @mbggenerated
     */
    private String shPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store_house.sh_address
     *
     * @mbggenerated
     */
    private String shAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store_house.sh_type
     *
     * @mbggenerated
     */
    private String shType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store_house.sh_remark
     *
     * @mbggenerated
     */
    private String shRemark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store_house.sh_id
     *
     * @return the value of store_house.sh_id
     *
     * @mbggenerated
     */
    public String getShId() {
        return shId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store_house.sh_id
     *
     * @param shId the value for store_house.sh_id
     *
     * @mbggenerated
     */
    public void setShId(String shId) {
        this.shId = shId == null ? null : shId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store_house.sh_name
     *
     * @return the value of store_house.sh_name
     *
     * @mbggenerated
     */
    public String getShName() {
        return shName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store_house.sh_name
     *
     * @param shName the value for store_house.sh_name
     *
     * @mbggenerated
     */
    public void setShName(String shName) {
        this.shName = shName == null ? null : shName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store_house.sh_responsible
     *
     * @return the value of store_house.sh_responsible
     *
     * @mbggenerated
     */
    public String getShResponsible() {
        return shResponsible;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store_house.sh_responsible
     *
     * @param shResponsible the value for store_house.sh_responsible
     *
     * @mbggenerated
     */
    public void setShResponsible(String shResponsible) {
        this.shResponsible = shResponsible == null ? null : shResponsible.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store_house.sh_phone
     *
     * @return the value of store_house.sh_phone
     *
     * @mbggenerated
     */
    public String getShPhone() {
        return shPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store_house.sh_phone
     *
     * @param shPhone the value for store_house.sh_phone
     *
     * @mbggenerated
     */
    public void setShPhone(String shPhone) {
        this.shPhone = shPhone == null ? null : shPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store_house.sh_address
     *
     * @return the value of store_house.sh_address
     *
     * @mbggenerated
     */
    public String getShAddress() {
        return shAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store_house.sh_address
     *
     * @param shAddress the value for store_house.sh_address
     *
     * @mbggenerated
     */
    public void setShAddress(String shAddress) {
        this.shAddress = shAddress == null ? null : shAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store_house.sh_type
     *
     * @return the value of store_house.sh_type
     *
     * @mbggenerated
     */
    public String getShType() {
        return shType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store_house.sh_type
     *
     * @param shType the value for store_house.sh_type
     *
     * @mbggenerated
     */
    public void setShType(String shType) {
        this.shType = shType == null ? null : shType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store_house.sh_remark
     *
     * @return the value of store_house.sh_remark
     *
     * @mbggenerated
     */
    public String getShRemark() {
        return shRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store_house.sh_remark
     *
     * @param shRemark the value for store_house.sh_remark
     *
     * @mbggenerated
     */
    public void setShRemark(String shRemark) {
        this.shRemark = shRemark == null ? null : shRemark.trim();
    }
}