package com.hehanpeng.ssm.module.account.pojo;

public class Account {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.acc_id
     *
     * @mbggenerated
     */
    private Integer accId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.acc_login
     *
     * @mbggenerated
     */
    private String accLogin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.acc_name
     *
     * @mbggenerated
     */
    private String accName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.acc_pass
     *
     * @mbggenerated
     */
    private String accPass;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.acc_id
     *
     * @return the value of account.acc_id
     *
     * @mbggenerated
     */
    public Integer getAccId() {
        return accId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.acc_id
     *
     * @param accId the value for account.acc_id
     *
     * @mbggenerated
     */
    public void setAccId(Integer accId) {
        this.accId = accId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.acc_login
     *
     * @return the value of account.acc_login
     *
     * @mbggenerated
     */
    public String getAccLogin() {
        return accLogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.acc_login
     *
     * @param accLogin the value for account.acc_login
     *
     * @mbggenerated
     */
    public void setAccLogin(String accLogin) {
        this.accLogin = accLogin == null ? null : accLogin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.acc_name
     *
     * @return the value of account.acc_name
     *
     * @mbggenerated
     */
    public String getAccName() {
        return accName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.acc_name
     *
     * @param accName the value for account.acc_name
     *
     * @mbggenerated
     */
    public void setAccName(String accName) {
        this.accName = accName == null ? null : accName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.acc_pass
     *
     * @return the value of account.acc_pass
     *
     * @mbggenerated
     */
    public String getAccPass() {
        return accPass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.acc_pass
     *
     * @param accPass the value for account.acc_pass
     *
     * @mbggenerated
     */
    public void setAccPass(String accPass) {
        this.accPass = accPass == null ? null : accPass.trim();
    }
}