package com.hehanpeng.ssm.module.accountRecods.pojo;

import java.math.BigDecimal;
import java.util.Date;

public class AccountRecords {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_records.ar_id
     *
     * @mbggenerated
     */
    private String arId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_records.sup_id
     *
     * @mbggenerated
     */
    private Integer supId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_records.ar_date
     *
     * @mbggenerated
     */
    private Date arDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_records.ar_order_id
     *
     * @mbggenerated
     */
    private String arOrderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_records.ar_bus_type
     *
     * @mbggenerated
     */
    private String arBusType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_records.ar_payable
     *
     * @mbggenerated
     */
    private BigDecimal arPayable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_records.ar_paid
     *
     * @mbggenerated
     */
    private BigDecimal arPaid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_records.ar_arrears
     *
     * @mbggenerated
     */
    private BigDecimal arArrears;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_records.ar_discount
     *
     * @mbggenerated
     */
    private BigDecimal arDiscount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_records.ar_attn
     *
     * @mbggenerated
     */
    private String arAttn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_records.ar_operator
     *
     * @mbggenerated
     */
    private Integer arOperator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_records.ar_remark
     *
     * @mbggenerated
     */
    private String arRemark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_records.ar_id
     *
     * @return the value of account_records.ar_id
     *
     * @mbggenerated
     */
    public String getArId() {
        return arId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_records.ar_id
     *
     * @param arId the value for account_records.ar_id
     *
     * @mbggenerated
     */
    public void setArId(String arId) {
        this.arId = arId == null ? null : arId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_records.sup_id
     *
     * @return the value of account_records.sup_id
     *
     * @mbggenerated
     */
    public Integer getSupId() {
        return supId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_records.sup_id
     *
     * @param supId the value for account_records.sup_id
     *
     * @mbggenerated
     */
    public void setSupId(Integer supId) {
        this.supId = supId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_records.ar_date
     *
     * @return the value of account_records.ar_date
     *
     * @mbggenerated
     */
    public Date getArDate() {
        return arDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_records.ar_date
     *
     * @param arDate the value for account_records.ar_date
     *
     * @mbggenerated
     */
    public void setArDate(Date arDate) {
        this.arDate = arDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_records.ar_order_id
     *
     * @return the value of account_records.ar_order_id
     *
     * @mbggenerated
     */
    public String getArOrderId() {
        return arOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_records.ar_order_id
     *
     * @param arOrderId the value for account_records.ar_order_id
     *
     * @mbggenerated
     */
    public void setArOrderId(String arOrderId) {
        this.arOrderId = arOrderId == null ? null : arOrderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_records.ar_bus_type
     *
     * @return the value of account_records.ar_bus_type
     *
     * @mbggenerated
     */
    public String getArBusType() {
        return arBusType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_records.ar_bus_type
     *
     * @param arBusType the value for account_records.ar_bus_type
     *
     * @mbggenerated
     */
    public void setArBusType(String arBusType) {
        this.arBusType = arBusType == null ? null : arBusType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_records.ar_payable
     *
     * @return the value of account_records.ar_payable
     *
     * @mbggenerated
     */
    public BigDecimal getArPayable() {
        return arPayable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_records.ar_payable
     *
     * @param arPayable the value for account_records.ar_payable
     *
     * @mbggenerated
     */
    public void setArPayable(BigDecimal arPayable) {
        this.arPayable = arPayable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_records.ar_paid
     *
     * @return the value of account_records.ar_paid
     *
     * @mbggenerated
     */
    public BigDecimal getArPaid() {
        return arPaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_records.ar_paid
     *
     * @param arPaid the value for account_records.ar_paid
     *
     * @mbggenerated
     */
    public void setArPaid(BigDecimal arPaid) {
        this.arPaid = arPaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_records.ar_arrears
     *
     * @return the value of account_records.ar_arrears
     *
     * @mbggenerated
     */
    public BigDecimal getArArrears() {
        return arArrears;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_records.ar_arrears
     *
     * @param arArrears the value for account_records.ar_arrears
     *
     * @mbggenerated
     */
    public void setArArrears(BigDecimal arArrears) {
        this.arArrears = arArrears;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_records.ar_discount
     *
     * @return the value of account_records.ar_discount
     *
     * @mbggenerated
     */
    public BigDecimal getArDiscount() {
        return arDiscount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_records.ar_discount
     *
     * @param arDiscount the value for account_records.ar_discount
     *
     * @mbggenerated
     */
    public void setArDiscount(BigDecimal arDiscount) {
        this.arDiscount = arDiscount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_records.ar_attn
     *
     * @return the value of account_records.ar_attn
     *
     * @mbggenerated
     */
    public String getArAttn() {
        return arAttn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_records.ar_attn
     *
     * @param arAttn the value for account_records.ar_attn
     *
     * @mbggenerated
     */
    public void setArAttn(String arAttn) {
        this.arAttn = arAttn == null ? null : arAttn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_records.ar_operator
     *
     * @return the value of account_records.ar_operator
     *
     * @mbggenerated
     */
    public Integer getArOperator() {
        return arOperator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_records.ar_operator
     *
     * @param arOperator the value for account_records.ar_operator
     *
     * @mbggenerated
     */
    public void setArOperator(Integer arOperator) {
        this.arOperator = arOperator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_records.ar_remark
     *
     * @return the value of account_records.ar_remark
     *
     * @mbggenerated
     */
    public String getArRemark() {
        return arRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_records.ar_remark
     *
     * @param arRemark the value for account_records.ar_remark
     *
     * @mbggenerated
     */
    public void setArRemark(String arRemark) {
        this.arRemark = arRemark == null ? null : arRemark.trim();
    }
}